lib/components/bottom_nav_bar/bottom_nav_bar.dart
lib/screens/create_or_edit_account_screen.dart
lib/screens/splash_screen.dart

- Speichern Button muss gesetzt werden (_setSaveButtonAnimation(true)) und Benutzer muss nach der Kontoerstellung auf die Kontoseite zurück navigiert werden.
- Erstellen Button auf Rund zurückgesetzt.
- Text optimiert.

Kontoerstellung Bugfix

---

lib/models/account.dart
lib/models/booking.dart
lib/screens/create_or_edit_account_screen.dart

- Wenn der Benutzer nun einen Kontonamen ändert werden bei allen Buchungen die auf dieses Konto verbucht wurden ebenfalls der Kontoname geändert/aktualisiert auf den neuen Kontoname. Neue Funktion: updateBookingAccountName(...).

Bugfix Kontoname ändern

---

lib/components/cards/monthly_overview_card.dart
lib/components/tab_views/yearly_booking_tab_view.dart

- Die jährliche Buchungsseiten UI wurde optimiert, damit es für den Benutzer übersichtlicher ist.
- Aktueller Monat wird zusätzlich hervorgehoben (farblich und dickere Schrift).
- Alter auskommentierter Code wurde entfernt.

Jährliche Buchungsseite optimiert

---

lib/components/cards/default_budget_card.dart
lib/components/cards/separate_budget_card.dart
lib/screens/edit_budget_screen.dart

- Beschreibungstext für Budgets und Standardbudgets bearbeiten hinzugefügt.
- Kleinere UI Verbesserungen.

Budgets bearbeiten UI verbessert

---

lib/models/categorie.dart
lib/models/enums/categorie_types.dart
lib/screens/budgets_screen.dart
lib/screens/introduction_screens.dart

- Bugfix Kategorie bearbeiten (Kategorienamen ändern) implementiert => type hat bei CategorieAdapter gefehlt dadurch wurden die Kategorien nicht richtig in Hive gespeichert. Type wurde in read und write Funktion hinzugefügt.
- Text von "Restliche Tage" auf "Verbleibende Tage" geändert.
- Alten Code entfernt.

Bugfix Kategorie bearbeiten

---

lib/models/booking.dart
lib/screens/create_or_edit_booking_screen.dart

- (Serien-)buchungen werden nun richtig vom ausgewählten Konto abgezogen bzw. übertragen.

Bugfix Serienbuchungen

---

lib/components/dialogs/list_dialog.dart
lib/components/input_fields/account_input_field.dart
lib/components/input_fields/categorie_input_field.dart
lib/components/input_fields/date_input_field.dart
lib/components/input_fields/money_input_field.dart
lib/components/input_fields/text_input_field.dart
lib/screens/create_or_edit_account_screen.dart
lib/screens/create_or_edit_booking_screen.dart
lib/screens/create_or_edit_budget_screen.dart
lib/screens/create_or_edit_categorie_screen.dart

Finales Bugfixing und Anpassungen der GUI.
1. Tasten für Betragseingabe
2. Auswahlfenster für Konten und Kategorie
Fehlertext bei vergessener Eingabe des Textes für Buchungen und Kategorien eingefügt.
Alle vorherigen PRs wurden aus dem main Branch bereits getestet und mit eingepflegt.

Pixel Bugfixing & GUI Verbesserungen

---

lib/components/input_fields/money_input_field.dart
lib/components/input_fields/text_input_field.dart
lib/screens/create_or_edit_booking_screen.dart

- Text löschen Icon wird nur angezeigt, wenn das Textfeld nicht leer ist.
- Betrag Bottom Sheet height verringert für weniger Abstand.

Text löschen optimiert

---

lib/components/input_fields/date_input_field.dart
lib/components/input_fields/text_input_field.dart

- Die Wiederholungs Auswahl wurde verbessert und wird nun über ein Bottom Sheet ausgewählt. Die aktuell ausgewählte Wiederholungsart wird ebenfalls markiert.
- Text Eingabefeld Default maxLength wurde auf 60 Zeichen erhöht (vorher 40 Zeichen).

Wiederholungs Auswahl verbessert

---

lib/components/dialogs/info_dialog.dart
lib/components/tab_views/asset_allocation_statistic_tab_view.dart
lib/screens/accounts_screen.dart

- Erklärungstext für Kapitalanlagen & risikolose Anlagen wurde hinzugefügt. Dialog wird bei Klick auf Hilfe Icon angezeigt.

#V1.0 Kapitalanlagen & risikolose Anlagen Erklärung

---

lib/components/cards/budget_card.dart
lib/components/cards/categorie_card.dart
lib/components/cards/categorie_percentage_card.dart
lib/components/input_fields/categorie_input_field.dart
lib/components/input_fields/subcategorie_input_field.dart
lib/components/tab_views/categorie_tab_view.dart
lib/main.dart
lib/models/categorie/categorie_interface.dart
lib/models/categorie/categorie_model.dart
lib/models/categorie/categorie_repository.dart
lib/models/enums/categorie_types.dart
lib/models/screen_arguments/create_or_edit_subcategorie_screen_arguments.dart
lib/screens/create_or_edit_booking_screen.dart
lib/screens/create_or_edit_budget_screen.dart
lib/screens/create_or_edit_categorie_screen.dart
lib/screens/create_or_edit_subcategorie_screen.dart
lib/screens/introduction_screens.dart
lib/screens/splash_screen.dart

Das Repository Pattern wurde für Kategorien umgesetzt und alter Code wurde entfernt. Neuer Code im Kategorien Repository wurde weiter optimiert. Funktionsaufrufe wurden ebenfalls auf neues Design Pattern umgestellt.
- categorie_interface.dart enthält alle Funktionsschnittstellen die auf Kategorien angewendet werden können.
- categorie_model.dart enthält alle Variablen + Hive Adapter für Kategorien.
- categorie_repository enthält alle Funktionen für Kategorien.

Repository Pattern für Kategorien implementiert

---

lib/components/cards/account_card.dart
lib/components/charts/future_wealth_development_chart.dart
lib/components/input_fields/account_input_field.dart
lib/components/tab_views/account_overview_tab_view.dart
lib/components/tab_views/asset_allocation_statistic_tab_view.dart
lib/components/tab_views/asset_development_statistic_tab_view.dart
lib/main.dart
lib/models/account/account_interface.dart
lib/models/account/account_model.dart
lib/models/account/account_repository.dart
lib/models/booking.dart
lib/models/screen_arguments/account_details_screen_arguments.dart
lib/screens/account_details_screen.dart
lib/screens/accounts_screen.dart
lib/screens/create_or_edit_account_screen.dart
lib/screens/introduction_screens.dart
lib/screens/splash_screen.dart

- Das Repository Pattern wurde für Konten umgesetzt.
- Gleiche Umsetzung wie für Kategorien.
**ACHTUNG:** Diese Version ist alleine nicht lauffähig, weil es Abhängigkeiten zu Buchungen (booking.dart) gibt. Wird mit der Umstellung von den Buchungen auf das Repository Pattern behoben.

Repository Pattern für Konten implementiert

---

lib/components/cards/booking_card.dart
lib/components/cards/categorie_percentage_card.dart
lib/components/charts/future_wealth_development_chart.dart
lib/components/charts/monthly_bar_chart.dart
lib/components/tab_views/account_overview_tab_view.dart
lib/components/tab_views/asset_development_statistic_tab_view.dart
lib/components/tab_views/monthly_booking_tab_view.dart
lib/components/tab_views/monthly_statistics_tab_view.dart
lib/components/tab_views/yearly_booking_tab_view.dart
lib/components/tab_views/yearly_statistics_tab_view.dart
lib/main.dart
lib/models/account/account_interface.dart
lib/models/account/account_model.dart
lib/models/account/account_repository.dart
lib/models/booking/booking_interface.dart
lib/models/booking/booking_model.dart
lib/models/booking/booking_repository.dart
lib/models/budget.dart
lib/models/categorie/categorie_model.dart
lib/models/categorie/categorie_repository.dart
lib/models/subbudget.dart
lib/models/wealth_development_stats.dart
lib/screens/accounts_screen.dart
lib/screens/create_or_edit_account_screen.dart
lib/screens/create_or_edit_booking_screen.dart

- Für Buchungen das Repository Pattern implementiert.

Buchungen Repository Pattern implementiert

---

lib/components/cards/budget_card.dart
lib/components/cards/edit_budget_card.dart
lib/components/cards/separate_budget_card.dart
lib/main.dart
lib/models/budget/budget_interface.dart
lib/models/budget/budget_model.dart
lib/models/budget/budget_repository.dart
lib/models/screen_arguments/edit_budget_screen_arguments.dart
lib/screens/budgets_screen.dart
lib/screens/create_or_edit_budget_screen.dart
lib/screens/edit_budget_screen.dart
lib/screens/overview_budgets_screen.dart

- Für Budget Repository Pattern implementiert.

Budget Repository Pattern implementieren

---

lib/components/input_fields/preselect_account_input_field.dart
lib/main.dart
lib/models/primary_account/primary_account_interface.dart
lib/models/primary_account/primary_account_model.dart
lib/models/primary_account/primary_account_repository.dart
lib/screens/create_or_edit_account_screen.dart
lib/screens/create_or_edit_booking_screen.dart
lib/screens/introduction_screens.dart
lib/screens/splash_screen.dart

- Für Primary Account das Repository Pattern implementiert.

Primary Account Repository Pattern implementiert

---

lib/components/cards/default_budget_card.dart
lib/main.dart
lib/models/budget/budget_interface.dart
lib/models/budget/budget_repository.dart
lib/models/categorie/categorie_model.dart
lib/models/default_budget/default_budget_interface.dart
lib/models/default_budget/default_budget_model.dart
lib/models/default_budget/default_budget_repository.dart
lib/models/subbudget/subbudget_repository.dart
lib/screens/create_or_edit_budget_screen.dart
lib/screens/edit_budget_screen.dart
lib/screens/edit_subbudget_screen.dart

- Für Standardbudget das Repository Pattern implementiert.
- Kleinere Code Verbesserungen implementiert Funktionsnamen wurden verbessert.

Standardbudget Repository Pattern implementiert

---

lib/main.dart
lib/models/booking/booking_repository.dart
lib/models/global_state/global_state_interface.dart
lib/models/global_state/global_state_model.dart
lib/models/global_state/global_state_repository.dart
lib/screens/introduction_screens.dart
lib/screens/splash_screen.dart

- Für Global State das Repository Pattern implementiert.

Global State Repository Pattern implementiert

---

lib/main.dart
lib/models/intro_screen_state/intro_screen_state_interface.dart
lib/models/intro_screen_state/intro_screen_state_model.dart
lib/models/intro_screen_state/intro_screen_state_repository.dart
lib/screens/settings_screen.dart
lib/screens/splash_screen.dart

- Für IntroScreen State das Repository Pattern implementiert.

IntroScreen State Repository Pattern implementiert

---

lib/components/cards/account_percentage_card.dart
lib/components/cards/categorie_percentage_card.dart
lib/components/tab_views/asset_allocation_statistic_tab_view.dart
lib/components/tab_views/monthly_statistics_tab_view.dart
lib/components/tab_views/yearly_statistics_tab_view.dart
lib/models/percentage_stats/percentage_stats_interface.dart
lib/models/percentage_stats/percentage_stats_model.dart
lib/models/percentage_stats/percentage_stats_repository.dart
lib/models/wealth_development_stats.dart

- Für Percentage Stats das Repository Pattern implementiert.

Percentage Stats Repository Pattern implementiert

---

lib/blocs/account_bloc/account_bloc.dart
lib/blocs/budget_bloc/budget_bloc.dart
lib/blocs/budget_bloc/budget_event.dart
lib/blocs/subbudget_bloc/subbudget_bloc.dart
lib/blocs/subbudget_bloc/subbudget_event.dart
lib/models/subbudget/subbudget_interface.dart
lib/models/subbudget/subbudget_repository.dart
lib/screens/budget_screens/overview_one_budget_screen.dart
lib/screens/budget_screens/overview_one_subbudget_screen.dart

- Budgets und Unterbudgets werden nun über Bloc gelöscht.

Delete budgets bloc pattern

---

lib/blocs/booking_bloc/booking_bloc.dart
lib/blocs/categorie_bloc/categorie_bloc.dart
lib/components/cards/categorie_percentage_card.dart
lib/components/charts/future_wealth_development_chart.dart
lib/components/charts/monthly_bar_chart.dart
lib/components/tab_views/asset_development_statistic_tab_view.dart
lib/components/tab_views/monthly_booking_tab_view.dart
lib/components/tab_views/monthly_statistics_tab_view.dart
lib/components/tab_views/yearly_booking_tab_view.dart
lib/components/tab_views/yearly_statistics_tab_view.dart
lib/models/account/account_repository.dart
lib/models/booking/booking_interface.dart
lib/models/booking/booking_repository.dart
lib/models/budget/budget_repository.dart
lib/models/subbudget/subbudget_repository.dart
lib/models/wealth_development_stats.dart
lib/screens/account_screens/account_details_screen.dart

- Bugfix 1: Balken werden wieder in der Kategorie Übersicht Statistik angezeigt.
- Bugfix 2: Buchungen für ein Konto werden wieder angezeigt, wenn auf ein Konto in der Konto Übersicht geklickt wird.
- Buchungsfunktionsnamen wurden verbessert.
- Monatliche Buchungsliste laden wurde in mehrere Funktionen aufgeteilt mit denen die Buchungsliste jeweils weiter nach unterschiedlichen Kriterien gefiltert werden kann.

Bugfix und Code Verbesserungen implementiert

---

lib/components/cards/categorie_card.dart

- Kategorie Karten UI + Unterkategorie Anzeige wurde verbessert.

Improve categorie card UI

---

lib/components/cards/categorie_card.dart
lib/components/cards/categorie_percentage_card.dart
lib/components/cards/edit_budget_card.dart
lib/screens/budget_screens/overview_all_budgets_screen.dart

- Budgets verwalten Seiten UI wurde verbessert + Budget editieren Karte wurde verbessert.
- Border wurde von ausgeklappten Karten entfernt.

Budgets verwalten Seiten UI wurde verbessert

---

lib/components/cards/categorie_percentage_card.dart
lib/components/tab_views/account_overview_tab_view.dart
lib/main.dart
lib/models/booking/booking_interface.dart
lib/models/booking/booking_repository.dart
lib/screens/account_screens/accounts_screen.dart
lib/screens/booking_screens/create_or_edit_booking_screen.dart

- Bei jedem neuen Start der App wird auf neue Buchungen geprüft und dementsprechend gebucht falls neue Buchungen seit dem letzten Start der App dazugekommen sind.
- Bei Buchung löschen Navigation richtig gesetzt.
- Kategorie Prozent Karten UI verbessert für 100.0 % Werte.
- Serienbuchungen werden jetzt für die nächsten 10 Jahre erstellt.

Auf neue Buchungen prüfen

---

lib/models/booking/booking_repository.dart

- Bug behoben bei prüfen auf neue Buchungen

Bug behoben bei prüfen auf neue Buchungen

---

lib/components/input_fields/text_input_field.dart
lib/models/global_state/global_state_repository.dart
lib/screens/account_screens/accounts_screen.dart
lib/screens/other_screens/introduction_screens.dart

- Startkonten werden jetzt auch beim ersten Start der App richtig angezeigt. Kommentar wurde im Code hinterlassen.
- Textfeld UX wurde verbessert.
- Kleinere Code Verbesserungen implementiert.

Startkonten Bug behoben

---

lib/components/buttons/month_picker_buttons.dart
lib/components/cards/account_card.dart
lib/components/cards/account_percentage_card.dart
lib/components/cards/booking_card.dart
lib/components/cards/budget_card.dart
lib/components/cards/categorie_card.dart
lib/components/cards/categorie_percentage_card.dart
lib/components/cards/default_budget_card.dart
lib/components/cards/edit_budget_card.dart
lib/components/cards/monthly_overview_card.dart
lib/components/cards/overview_tile_card.dart
lib/components/cards/separate_budget_card.dart
lib/components/cards/separate_subbudget_card.dart
lib/components/tab_views/account_overview_tab_view.dart
lib/components/tab_views/monthly_booking_tab_view.dart
lib/components/tab_views/monthly_statistics_tab_view.dart
lib/components/tab_views/yearly_booking_tab_view.dart
lib/components/tab_views/yearly_statistics_tab_view.dart
lib/utils/consts/global_consts.dart
pubspec.lock
pubspec.yaml

- Erste Animationen für Karten implementiert.
- Erste Animationen für Statistiken implementiert.

Erste Animationen implementiert

---

lib/blocs/account_bloc/account_bloc.dart
lib/blocs/booking_bloc/booking_bloc.dart
lib/blocs/budget_bloc/budget_bloc.dart
lib/blocs/button_blocs/transaction_stats_toggle_buttons_bloc/transaction_stats_toggle_buttons_cubit.dart
lib/blocs/default_budget_bloc/default_budget_bloc.dart
lib/blocs/input_field_blocs/money_input_field_bloc/money_input_field_cubit.dart
lib/blocs/input_field_blocs/money_input_field_bloc/money_input_field_model.dart
lib/blocs/subbudget_bloc/subbudget_bloc.dart
lib/components/input_fields/money_input_field.dart
lib/models/booking/booking_model.dart
lib/models/booking/booking_repository.dart
lib/models/enums/amount_types.dart
lib/models/enums/transaction_types.dart
lib/screens/booking_screens/create_or_edit_booking_screen.dart

- Der Benutzer kann nun einen Betragstyp auswählen. Bei Einnahmen: Nicht definiert, passiv oder aktiv. Bei Ausgaben: Nicht definiert, Fix oder Variabel.
- Betragstyp wurde in Buchungsdatenstruktur aufgenommen.

Betragstyp implementiert

---

lib/components/input_fields/money_input_field.dart
lib/models/booking/booking_model.dart
lib/screens/other_screens/settings_screen.dart

- Für den Betragstyp wurde ein kleiner Hilfetext implementiert, der über das Fragezeichen Icon im Bottom Sheet erreichbar ist, um dem Benutzer die Begriffe: Fix und Variable Ausgaben und Aktive und Passive Einnahmen zu erklären.

Betragstyp Hilfetext implementiert

---

lib/blocs/booking_bloc/booking_bloc.dart
lib/components/input_fields/money_input_field.dart
lib/models/booking/booking_repository.dart

- Einzelnes Symbol bei Betrag kann wieder gelöscht werden.
- Beim Updaten einer Einzelbuchung zu einer Serienbuchung wird dies korrekt abgehandelt.
- Bei Änderung der Wiederholungsart einer Serienbuchung wird dies korrekt abgehandelt.

Buchungs Bugs behoben

---

lib/components/tab_views/asset_development_statistic_tab_view.dart
lib/components/tab_views/asset_development_statistic_tab_view_old.dart
lib/models/booking/booking_repository.dart

- Vermögensentwicklung Statistik angefangen, wird unter der Einnahmen und Ausgaben Statistik angezeigt.

Vermögensentwicklung Statistik angefangen

---

android/app/build.gradle
android/build.gradle
lib/main.dart
pubspec.lock
pubspec.yaml

Flutter Packages geupdatet
